### ISSUE TITLE
error in normalization

### ISSUE THREAD

**Issue by simongalasso** [DiMasta/MarLanderEpisode2#1]
Hello,

In the function Chromosome::evaluate(), you are dividing the distance by MAX_DISTANCE that equal to sqrt((w * w) + (h * h)).
But because you are following the zones from the crash to the landing, and adding their length to calculate the distance, it mean that the distance can be bigger than MAX_DISTANCE, in that case the value is not normalized between 0 and 1.

Maybe you could get the sum of the ground lines length and divide distance by that value.

Btw, thanks for your post on CG, it helped a lot !

**Comment by DiMasta** [comment]
Yeap, you're right, nice catch, thanks. I'm glad that my article have helped you :)
